# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-14 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import risk_type.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('risk_type', models.CharField(choices=[(risk_type.enums.RiskTypes('automobile'), 'automobile'), (risk_type.enums.RiskTypes('house'), 'house'), (risk_type.enums.RiskTypes('prize'), 'prize')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('dtype', models.CharField(choices=[(risk_type.enums.DataTypes('text'), 'text'), (risk_type.enums.DataTypes('number'), 'number'), (risk_type.enums.DataTypes('date'), 'date'), (risk_type.enums.DataTypes('enum'), 'enum')], max_length=5)),
                ('description', models.TextField(default='')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riskfields', to='risk_type.Risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFieldEnumOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=10)),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='risk_type.RiskField')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFieldSuCl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFieldDate',
            fields=[
                ('riskfieldsucl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_type.RiskFieldSuCl')),
                ('value', models.DateField()),
            ],
            bases=('risk_type.riskfieldsucl',),
        ),
        migrations.CreateModel(
            name='RiskFieldEnum',
            fields=[
                ('riskfieldsucl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_type.RiskFieldSuCl')),
                ('value', models.CharField(max_length=10)),
            ],
            bases=('risk_type.riskfieldsucl',),
        ),
        migrations.CreateModel(
            name='RiskFieldNumber',
            fields=[
                ('riskfieldsucl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_type.RiskFieldSuCl')),
                ('value', models.FloatField()),
            ],
            bases=('risk_type.riskfieldsucl',),
        ),
        migrations.CreateModel(
            name='RiskFieldText',
            fields=[
                ('riskfieldsucl_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='risk_type.RiskFieldSuCl')),
                ('value', models.TextField()),
            ],
            bases=('risk_type.riskfieldsucl',),
        ),
        migrations.AddField(
            model_name='riskfieldsucl',
            name='risk_field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_type.RiskField'),
        ),
    ]
