# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-08-14 06:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('risk_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='risk_type.Risk'),
        ),
    ]
